version: '3.8'
services:
  web:
    container_name: demo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/qra
    environment:
      - MONGODB_URI=mongodb://mongo:cE4H32fC3Hfb2CCe1d4CC4BbGgDdDBCH@roundhouse.proxy.rlwy.net:24701
      - PORT=4000
      - NODE_ENV=development
    command: /bin/sh -c 'npm install && npm run dev'
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - volumedemo:/data/db
volumes:
  volumedemo:
