version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/qr # Se utiliza host.docker.internal para acceder al sistema host
      - PORT=4000
      - NODE_ENV=development
    command: /bin/sh -c 'npm install && npm run dev'
