version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    links:
      - mongo
    volumes:
      - .:/qra # Asegúrate de que el punto se refiere al directorio raíz del proyecto
    environment:
      - MONGODB_URI=mongodb://mongo/notesdb
      - PORT=4000
      - NODE_ENV=development
    command: /bin/sh -c 'npm install && npm run dev'
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - volumedemo:/data/db

volumes:
  volumedemo: